# MCTS part

In [168]:
class dotdict(dict):
    def __getattr__(self, name):
        return self[name]
args = dotdict({
    'numIters': 1000,
    'numEps': 100,
    'tempThreshold': 15,
    'updateThreshold': 0.55,
    'maxlenOfQueue': 200000,
    'numMCTSSims': 25,
    'arenaCompare': 40,
    'cpuct': 1,

    'checkpoint': './temp/',
    'load_model': True,
    'load_folder_file': ('./temp/','checkpoint_5.pth.tar'),
    'numItersForTrainExamplesHistory': 20,

})

class NNet():
    def predict(canonicalBoard):
        return np.ones([9,9])
    
class Game():
    def getGameEnded
    def stringRepresentation
    def getActionSize
    def getValidMoves

In [166]:
nnet=NNet()
mcts=MCTS(nnet,args)

# GameLogic Part

In [134]:
'''
Author: Miaozha
Date: 5 23, 2019.
Board class.
Board data:
  1=cricle, -1=cross, 0=empty
  first dim is column , 2nd is row:
     pieces[1][7] is the square in column 2,
     at the opposite end of the board in row 8.
Squares are stored and manipulated as (x,y) tuples.
x is the column, y is the row.
'''
import numpy as np
class Board():

    def __init__(self):
        "Set up initial board configuration."
        self.pieces = np.zeros([9,9],dtype=np.int8)
        self.main_pieces= np.zeros([3,3],dtype=np.int8)
        self.main_pieces_finished= np.zeros([3,3],dtype=np.int8)
        self.last_move=None
        self.activation_zone=None
        self.finished=False
        self.winner=0
        
    # add [][] indexer syntax to the Board
    def __getitem__(self, index): 
        return self.pieces[index]

    def countDiff(self, color):
        """Counts the # pieces of the given color"""
        return np.sum(self.pieces)

    def get_legal_moves(self, color):
        """Returns all the legal moves for the given color.
        """
        moves = set()  # stores the legal moves.
        
        if self.activation_zone==None:
            return np.where(self.pieces==0)
        
        sub_board=self.get_sub_board(self.activation_zone)
        legal_indices_sub=np.where(sub_board==0)
        return to_board_index(legal_indices_sub,self.activation_zone)

    def has_legal_moves(self, color):
        return not self.finished

    def execute_move(self, move, color):
        """Perform the given move on the board; flips pieces as necessary.
        color gives the color pf the piece to play 
        """
        # update board
        x,y=move
        self.pieces[x,y]=color
        
        self.last_move=[[x//3,y//3],[x%3,y%3]]
        last_move_zone_x,last_move_zone_y=self.last_move[0]
        last_move_sub_x,last_move_sub_y=self.last_move[1]
        
        # update the status of the current subboard to the main board
        if sub_board_win(self.get_sub_board(self.last_move[0]),self.last_move[1]):
            self.main_pieces[last_move_zone_x,last_move_zone_y]=color
            self.main_pieces_finished=1
            # check whether the current color wins:
            if sub_board_win(self.main_pieces,self.last_move[0]):
                self.finish=True
                self.winner=color
        elif len(np.where(self.get_sub_board(self.last_move[0]))[0])==0:
            self.main_pieces_finished=1
        
        # update the new activation zone
        if self.main_pieces_finished[last_move_sub_x,last_move_sub_y]==0:
            self.activation_zone=self.last_move[1]
        else:
            self.activation_zone=None

    def get_sub_board(self,move):
        x,y=move
        return self.pieces[3*x:3*x+3,3*y:3*y+3]

    def to_board_index(index_at_sub_board,sub_board_index):
        index_at_sub_board_x,index_at_sub_board_y=index_at_sub_board
        sub_board_x,sub_board_y=sub_board_index
        return np.asarray([index_at_sub_board_x+3*sub_board_x,index_at_sub_board_y+3*sub_board_y])

    def fill_test_pattern(self):
        for i in range(9):
            for j in range(9):
                next_move(self.pieces,i,j,i*10+j)

    def sub_board_win(sub_board,last_move):
        last_x,last_y=last_move
        last_c=sub_board[last_x,last_y]
        if len(set(sub_board[last_x]))==1:
            return True
        if len(set(sub_board[:,last_y]))==1:
            return True
        if last_x==last_y and len(set([sub_board[0,0],sub_board[1,1],sub_board[2,2]]))==1:
            return True
        if last_x+last_y==2 and len(set([sub_board[0,2],sub_board[1,1],sub_board[2,0]]))==1:
            return True
        return False

In [135]:
b=Board()

In [156]:
b.pieces

array([[ 1, -1,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [157]:
b.countDiff(1)

1

In [158]:
b.get_legal_moves(1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]], dtype=int64)

In [159]:
b.has_legal_moves(1)

True

In [160]:
b.execute_move((0,5),1)

In [39]:
# def init_board(board):
#     board=np.zeros([9,9],dtype=np.int8)

def next_move(board,move,c):
    x,y=move
    board[x,y]=c
    return(x,y)

def get_sub_board(board,move):
    x,y=move
    return board[3*x:3*x+3,3*y:3*y+3]

def to_board_index(index_at_sub_board,sub_board_index):
    index_at_sub_board_x,index_at_sub_board_y=index_at_sub_board
    sub_board_x,sub_board_y=sub_board_index
    return np.asarray([index_at_sub_board_x+3*sub_board_x,index_at_sub_board_y+3*sub_board_y])

def fill_test_pattern(board):
    for i in range(9):
        for j in range(9):
            next_move(board,i,j,i*10+j)
            
def sub_board_win(sub_board,last_move):
    last_x,last_y=last_move
    last_c=sub_board[last_x,last_y]
    if len(set(sub_board[last_x]))==1:
        return True
    if len(set(sub_board[:,last_y]))==1:
        return True
    if last_x==last_y and len(set([sub_board[0,0],sub_board[1,1],sub_board[2,2]]))==1:
        return True
    if last_x+last_y==2 and len(set([sub_board[0,2],sub_board[1,1],sub_board[2,0]]))==1:
        return True
    return False

In [34]:
board=np.zeros([9,9],dtype=np.int8)
# fill_test_pattern(board)

In [27]:
print(board)

[[ 0  1  2  3  4  5  6  7  8]
 [10 11 12 13 14 15 16 17 18]
 [20 21 22 23 24 25 26 27 28]
 [30 31 32 33 34 35 36 37 38]
 [40 41 42 43 44 45 46 47 48]
 [50 51 52 53 54 55 56 57 58]
 [60 61 62 63 64 65 66 67 68]
 [70 71 72 73 74 75 76 77 78]
 [80 81 82 83 84 85 86 87 88]]


In [44]:
len(np.where(board!=0)[0])

0

In [37]:
to_board_index(np.where(get_sub_board(board,2,2)==0),2,2)

array([[6, 6, 6, 7, 7, 7, 8, 8, 8],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]], dtype=int64)

In [9]:
subboard=np.zeros([3,3],dtype=np.int8)

In [13]:
print(subboard)

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [26]:
subboard=np.zeros([3,3],dtype=np.int8)
print(subboard)
print(sub_board_win(subboard,next_move(subboard,0,0,1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,2,2,-1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,0,2,1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,0,1,-1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,2,0,1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,1,0,-1)))
print(subboard)
print(sub_board_win(subboard,next_move(subboard,1,1,1)))
print(subboard)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
0
[[ 1  0  0]
 [ 0  0  0]
 [ 0  0 -1]]
0
[[ 1  0  1]
 [ 0  0  0]
 [ 0  0 -1]]
0
[[ 1 -1  1]
 [ 0  0  0]
 [ 0  0 -1]]
0
[[ 1 -1  1]
 [ 0  0  0]
 [ 1  0 -1]]
0
[[ 1 -1  1]
 [-1  0  0]
 [ 1  0 -1]]
1
[[ 1 -1  1]
 [-1  1  0]
 [ 1  0 -1]]


In [17]:
sub_board_win(subboard,(1,1))

0