In [1]:
from Game.GameLogic import Board
from random import choice as randchoice
import numpy as np
from copy import deepcopy as copy
from tqdm import tqdm_notebook as tqdm
import pickle

In [2]:
def one_search(board,color):
    b=copy(board)
    current_color=copy(color)
    while not b.finished:
        move=randchoice(b.get_legal_moves(current_color))
    #         print(move+1)
        b.execute_move(move,current_color)
        current_color*=-1
    return b.winner

def search_one_move(board,move,color,times):
    b=copy(board)
    current_color=copy(color)
    b.execute_move(move,current_color)
    return sum([one_search(b,-current_color) for i in range(times)])

def search_next(board,color,times):
    time_start=time.time()
    moves=board.get_legal_moves(color)
    times_each=times//len(moves)
    print('search {} times for each move.'.format(times_each))
    move_value=[None]*len(moves)
    for i in tqdm(range(len(moves))):
        move_value[i]=search_one_move(board,moves[i],color,times_each)
    time_end=time.time()
    print('time cost',time_end-time_start,'s')
    return np.array(move_value)

In [3]:
b=Board(9)
current_color=1

In [4]:
b.tostring()

b'\x80\x03cGame.GameLogic\nBoard\nq\x00)\x81q\x01}q\x02(X\x06\x00\x00\x00piecesq\x03cnumpy.core.multiarray\n_reconstruct\nq\x04cnumpy\nndarray\nq\x05K\x00\x85q\x06C\x01bq\x07\x87q\x08Rq\t(K\x01K\tK\t\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i1q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89CQ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00q\x11tq\x12bX\x0b\x00\x00\x00main_piecesq\x13h\x04h\x05K\x00\x85q\x14h\x07\x87q\x15Rq\x16(K\x01K\x03K\x03\x86q\x17h\x0e\x89C\t\x00\x00\x00\x00\x00\x00\x00\x00\x00q\x18tq\x19bX\x14\x00\x00\x00main_pieces_finishedq\x1ah\x04h\x05K\x00\x85q\x1bh\x07\x87q\x1cRq\x1d(K\x01K\x03K\x03\x86q\x1eh\x0e\x89C\t\x00\x00\x00\x00\x00\x

In [230]:
print('value : {}'.format(np.array(move_value).sum()/20000))
next_move=b.get_legal_moves(current_color)[np.array(move_value).argmax()]
print(next_move+1)

value : -0.40495
[7 7]


In [231]:
b.execute_move(next_move,current_color)
current_color*=-1

In [232]:
b.execute_move(np.array([2,5])-1,current_color)
current_color*=-1

In [233]:
b.pieces

array([[ 0,  0,  1, -1,  1,  1,  1, -1,  0],
       [-1,  1,  0,  1, -1,  0,  0,  1,  0],
       [ 1,  0,  0,  0,  0, -1,  0, -1,  0],
       [ 0,  0, -1, -1,  0,  0,  0, -1,  0],
       [ 1,  0, -1, -1,  1,  0,  0,  0,  1],
       [-1,  1, -1, -1,  0,  0,  0,  1,  0],
       [-1, -1,  0,  0,  0, -1,  1,  0,  0],
       [ 1,  0,  0,  0,  0, -1,  1,  1,  0],
       [ 1,  0, -1,  0,  1, -1,  1,  0,  0]], dtype=int8)

In [229]:
move_value=search_next(b,current_color,20000)

search 3333 times for each move.


time cost 25.13786292076111 s


In [235]:
b.winner

-1

In [106]:
init_value=(
    np.array([ -1,  14,  26,  -6,  -8,  -5,   2,  18,  12,  20,  -4,  14,  -1,
        -5, -11,   6,  13,   7,   2,  12,   7,  -7,  20,  -5,  17,   1,
         2,   6,  15,  12,  14,   2,  19,  -3,  10,   2,  -1,  -7,  -3,
        14,  22,  24,  -3,  -2,  15, -14,   8,  -7,  16,   9,   1,  -6,
         5, -16,  12,  -6,   9,  -9,  12,  17,  11,  15,   0,   9,  -8,
        15,   4,  10,   9, -10,   5,  -3,   6,   9,   4,  -7,  -2, -11,
        19, -10,  15])+
    np.array([ 88,  97,  76,  89,  47,  43,  95,  27,  64, 118, 108,  56,  53,
        28,  78,  82,  69,  89,  95,  61, 115, -23,  11,  35,  77, 100,
        45,  25,  41, -19, 113,  55, 128,  79,  18,  19,  71,  45, -54,
       103, 123, 123,  23,   1,  49, -14,  -2,  47, 157,  80, 109, -11,
        38,   8, 128,  41,  74,  29,  36,   3, 103, 107,  97,  37,  74,
        55,  22,   8,  80,  53,  70,  88,  60,  87, 118,  50,  51,  -1,
        79,  73,  93])+
    np.array([ 64,  68,  70,  20,  87,  24,  36,  85, 118,  39,  99, 101,  44,
       -35,  19, 105, 106, 135,  88,  69, 122,  39,  63, -14,  83,  72,
        73,  15,  86,  84, 146,  73,  75, -23, 114,  59,  49,  36,  25,
        67, 204,  63,  80,   6,  61,  52, -13, -11, 111, 162,  88,  24,
        31,  20,  45,  14,  28, -22,  10,  88,  66,  47,  -2,  35,  88,
       123,  25,  20,  18,  29,  61,  42, 110,  66,  45,  10,  66,  -6,
       -13,  66,  44])
).reshape(9,9)

In [107]:
init_symmetrized=np.zeros((9,9),dtype=np.int32)
for i in range(1,5):
    init_symmetrized+=np.rot90(init_value,i)
    init_symmetrized+=np.rot90(np.fliplr(init_value),i)

In [109]:
init_symmetrized.reshape(-1).argmax()

40

In [29]:
def one_search(board,color):
    b=copy(board)
    current_color=copy(color)
    while not b.finished:
        move=randchoice(b.get_legal_moves(current_color))
    #         print(move+1)
        b.execute_move(move,current_color)
        current_color*=-1
    return b.winner

In [51]:
np.array([1,2,3]).argmax()

2

In [47]:
import time

time_start=time.time()
print(sum([one_search(b,current_color) for i in range(10000)]))
time_end=time.time()
print('time cost',time_end-time_start,'s')

576
time cost 54.88543772697449 s


In [24]:
b.pieces

array([[ 1,  1, -1,  0,  1, -1, -1,  1,  1],
       [-1, -1,  1,  1, -1, -1,  1, -1,  1],
       [ 1, -1,  1, -1, -1, -1,  1,  1, -1],
       [-1,  0,  1,  1,  0,  1,  0,  1, -1],
       [-1, -1,  1,  0,  0,  1,  1, -1, -1],
       [ 0, -1, -1,  0,  0,  1,  1,  1, -1],
       [-1,  1, -1, -1, -1,  1, -1,  1, -1],
       [-1,  0,  1, -1, -1, -1,  1, -1, -1],
       [-1,  1, -1,  1,  1,  1,  1,  1,  1]], dtype=int8)

In [25]:
b1.pieces

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [10]:
import time

time_start=time.time()
for i in range(100):
    b=Board(9)
    current_color=1
    while not b.finished:
        move=randchoice(b.get_legal_moves(current_color))
#         print(move+1)
        b.execute_move(move,current_color)
        current_color*=-1
    print(b.finished,b.winner)
time_end=time.time()
print('time cost',time_end-time_start,'s')

True 1
True 1
True -1
True -1
True -1
True -1
True 1
True 1
True 0
True -1
True 1
True -1
True -1
True 1
True 1
True 0
True 0
True 1
True -1
True 0
True 1
True 0
True 1
True 1
True -1
True 0
True 1
True 1
True -1
True 1
True 0
True 1
True -1
True 1
True -1
True -1
True -1
True 0
True -1
True -1
True 0
True 1
True 0
True 1
True 1
True 1
True 0
True -1
True 1
True -1
True -1
True -1
True -1
True 1
True 0
True 1
True -1
True 1
True 0
True 0
True -1
True -1
True -1
True 1
True -1
True 0
True 0
True -1
True 1
True 1
True 1
True -1
True 0
True 0
True -1
True 1
True -1
True -1
True 1
True 1
True -1
True 1
True -1
True 1
True -1
True 0
True -1
True 0
True 1
True 1
True -1
True -1
True 1
True -1
True -1
True -1
True 1
True 1
True 0
True -1
time cost 0.5495250225067139 s


In [4]:
(b.finished,b.winner)

(True, -1)

In [5]:
b.main_pieces_finished

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 1]], dtype=int8)

In [6]:
b.pieces

array([[ 0,  0, -1,  1,  0, -1,  1,  0,  1],
       [ 0,  1, -1,  0,  1,  0,  1,  1,  1],
       [ 0,  0, -1,  0,  0,  1, -1,  1,  0],
       [-1, -1, -1, -1,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  1, -1,  1,  1,  0, -1],
       [ 1, -1, -1,  1,  0, -1,  1,  0, -1],
       [-1,  0, -1,  1, -1, -1,  1,  0,  0],
       [ 1,  0,  0, -1,  0,  0,  1,  0,  0],
       [-1,  1, -1,  0,  1,  0,  1, -1,  1]], dtype=int8)

In [7]:
b.main_pieces

array([[-1,  1,  1],
       [-1, -1, -1],
       [ 0,  0,  1]], dtype=int8)

In [10]:
randchoice(b.get_legal_moves(current_color))

array([2, 2], dtype=int64)

In [11]:
b.get_legal_moves(current_color)

array([[2, 1],
       [2, 2]], dtype=int64)

In [241]:
import pickle
class test():
    def __init__(self):
        self.value=1
    def tostring(self):
        return pickle.dumps(self)

In [242]:
t=test()

In [245]:
t2=pickle.loads(t.tostring())

In [246]:
t2.value

1